# Lab Report - Multiple Template Match Scenario
# Patient: Kiki Appgoal (exists in DB)
# Reviewer: Andrea Franchett (exists in DB - direct match)
# Templates: CBC + CMP will match multiple lab templates
# Pages: 2 (comprehensive panel)

patient:
  first_name: "Kiki"
  last_name: "Appgoal"
  date_of_birth: "1955-12-12"
  mrn: "472775925"

reviewer:
  first_name: "Andrea"
  last_name: "Franchett"
  npi: ""

report:
  type: "lab_report"
  date: "2026-02-03"
  facility: "Canvas Medical Laboratory"

pages: 2
